name: Build

on:
  workflow_call:
    inputs:
      deploy:
        description: "Deploy the app"
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building..."
      - run: echo "Deploying..."
        if: ${{ inputs.deploy }}
