name: Build

on:
  workflow_call:
    inputs:
      deploy:
        description: "Deploy the app"
        required: false
        type: boolean

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      app_url: ${{ steps.prepare.outputs.app_url }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "Preparing..."
      - shell: bash
        id: prepare
        run: |
          if [ ${{ github.event_name }} == 'release' ]; then
            echo "app_url=nexus-docs-cms.ue1.staging.spoton.sh" >> "$GITHUB_OUTPUT"
          else
            echo "app_url=pr-${{ github.event.number }}-nexus-docs-cms.ue1.dev.spoton.sh" >> "$GITHUB_OUTPUT"
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ needs.prepare.outputs.app_url }}
      - run: echo "Deploying..."
        if: ${{ inputs.deploy }}
