name: Destroy Preview

on:
  pull_request:
    -types: [closed]

permissions:
  contents: write
  pages: write
  pull-requests: write

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Destroy preview
        uses: rossjrw/pr-preview-action@v1
