name: 'Create Release'
on:
  push:
    branches: [main]
    
jobs:
  main:
    runs-on: [self-hosted, corp, medium, eks-runner]
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Release'
      uses: spotoninc/github-action-create-release@v1
