name: Main

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.6.0"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ github.event_name == 'pull_request' && steps.preview.outputs.deployment-url || '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy preview
        id: preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
      - name: Deploy main
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean-exclude: pr-preview/
          force: false
          folder: ./dist/
