name: Release

on:
  pull_request:
    types: [ready_for_review]

jobs:
  test:
    if:  startsWith(github.head_ref, 'changeset-release/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "dummy build"
