name: Release

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled, synchronized ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{github.event.pull_request.head.ref}}"
