name: Release

on:
  pull_request:
    types: [ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '21.0.0'
      - run: npm --version
